import { Link } from 'react-router-dom';
import Timeline from '../components/ui/Timeline';
import LeadershipSection from '../components/ui/LeadershipSection';
import TeamSection from '../components/ui/TeamSection';
import SEO from '../components/common/SEO';
import styles from './About.module.css';

// Timeline images
import timeline1987 from '../assets/about/original-roc-1987.webp';
import timeline2001 from '../assets/about/a2z-storefront.webp';
import timeline2010 from '../assets/projects/Greenprint Apartments_Phoenix AZ.webp';
import timeline2024Vegas from '../assets/portfolio/commercial/Bettys_Village_Cover_Las_Vegas_NV.webp';
import timeline2016 from '../assets/about/hvac-van-2016.webp';
import timeline2024 from '../assets/projects/Aquila Place_ Apache Junction_(2).webp';

// Hero image (1200w original + 640w / 960w variants generated by scripts/generate-hero-variants.mjs)
import heroImage      from '../assets/projects/Hyundai Gilbert_Gilbert Az.webp';
import heroImage640w  from '../assets/projects/Hyundai Gilbert_Gilbert Az-640w.webp';
import heroImage960w  from '../assets/projects/Hyundai Gilbert_Gilbert Az-960w.webp';
import droneTeamImg from '../assets/about/drone-team.webp';

const About = () => {
    const values = [
        {
            title: "One Team",
            description: "By self-performing our trades, we control the schedule, quality, and safety of every project. No finger-pointing, just results."
        },
        {
            title: "Integrity First",
            description: "We stand behind our word and our work. Relationships built on trust last longer than any building we construct."
        },
        {
            title: "Safety Always",
            description: "Everyone goes home safe. Our commitment to safety isn't a checkbox. It's woven into everything we do."
        },
        {
            title: "Quality Obsessed",
            description: "We obsess over every detail because our name is on every project. Good enough isn't in our vocabulary."
        }
    ];

    const timelineEvents = [
        {
            year: "1987",
            title: "The Original License",
            description: "Arizona ROC issues License No. 074485 to A-2-Z Roofing Supply Co. — the company whose 2020 merger with Canyon State brought 33 years of roofing pedigree under one roof.",
            image: timeline1987
        },
        {
            year: "2001",
            title: "Small Beginnings",
            description: "Founded in Kingman with a single roofing crew and a commitment to quality that set us apart from day one.",
            image: timeline2001
        },
        {
            year: "2016",
            title: "Going Multi-Trade",
            description: "Launched the HVAC division, beginning the shift from a single-trade roofer to the multi-trade construction company Canyon State is today.",
            image: timeline2016
        },
        {
            year: "2020",
            title: "Merger & Expansion",
            description: "Canyon State merged with A-2-Z Roofing, doubling crew capacity and prompting the first major expansion of our Kingman headquarters.",
            image: timeline2010
        },
        {
            year: "2024",
            title: "Nevada Operations",
            description: "Opened the Las Vegas branch, putting Canyon State crews on the Strip corridor and across Southern Nevada.",
            image: timeline2024Vegas
        },
        {
            year: "2025",
            title: "Three Moves in One Year",
            description: "Merged stucco operations with Gonzalez Wall Systems, opened a second Kingman expansion, and acquired Kingman Quality Plumbing.",
            image: timeline2024
        }
    ];

    return (
        <div className="about-page">
            <SEO
                title="About Us - Our Story & Leadership"
                description="Since 2001, Canyon State Enterprises has built the Southwest with 12+ self-performed construction trades across Arizona, Nevada, Utah, and New Mexico."
                canonical="https://canyonstateaz.com/about"
            />
            {/* Full-Bleed Hero */}
            <section className={styles.fullHero}>
                {/* Real <img> (not CSS bg) so the preload scanner discovers
                    the LCP image and prioritizes it. */}
                {/* width/height = intrinsic source (1200x449) so browser reserves
                    aspect-ratio-correct space before pixels arrive. CSS object-fit
                    in .heroBg still drives the rendered cover behavior.
                    srcSet lets the browser pick the smallest variant that fits
                    the viewport — phones get the 32 kB 640w image instead of 243 kB. */}
                <img
                    className={styles.heroBg}
                    src={heroImage}
                    srcSet={`${heroImage640w} 640w, ${heroImage960w} 960w, ${heroImage} 1200w`}
                    sizes="100vw"
                    alt=""
                    aria-hidden="true"
                    width={1200}
                    height={449}
                    fetchPriority="high"
                    loading="eager"
                    decoding="async"
                />
                <div className={styles.heroOverlay}></div>
                <div className={styles.heroContent}>
                    <span className={styles.heroLabel}>ABOUT US</span>
                    <h1 className={styles.heroHeadline}>We Are<br />Canyon State</h1>
                    <p className={styles.heroSubline}>Arizona roots. Southwest reach. One team.</p>
                </div>
            </section>

            {/* Our Story Section */}
            <section className={styles.storySection}>
                <div className="container">
                    <div className={styles.storyGrid}>
                        <div className={styles.storyHeading}>
                            <h2>Our Story</h2>
                        </div>
                        <div className={styles.storyContent}>
                            <p>
                                Canyon State Enterprises was founded on a simple principle: do good work, and treat people right.
                                What started as a small local operation has grown into a multi-trade powerhouse serving the entire Southwest.
                            </p>
                            <p>
                                We believe in the power of "One Team." By self-performing many of our trades, we control the schedule,
                                the quality, and the safety of every project. When you work with Canyon State, you're not hiring a
                                general contractor who subs everything out. You're partnering with craftsmen who take personal pride in their work.
                            </p>
                            <p>
                                From roofing to stucco, HVAC to full construction services, our integrated approach means fewer delays,
                                better communication, and superior quality control. One team. Multiple trades. Zero excuses.
                            </p>
                        </div>
                    </div>
                </div>
            </section>

            {/* Values Section */}
            <section className={styles.valuesSection}>
                <div className="container">
                    <div className={styles.valuesHeader}>
                        <h2>What We Stand For</h2>
                        <p>Our values aren't wall decorations. They're how we make decisions every day.</p>
                    </div>
                    <div className={styles.valuesGrid}>
                        {values.map((value, index) => (
                            <div key={index} className={styles.valueCard}>
                                <span className={styles.valueNumber}>0{index + 1}</span>
                                <h3>{value.title}</h3>
                                <p>{value.description}</p>
                            </div>
                        ))}
                    </div>
                </div>
            </section>

            {/* Timeline Section */}
            <section className={styles.timelineSection}>
                <div className="container">
                    <div className={styles.timelineHeader}>
                        <h2>Our Journey</h2>
                        <p>Nearly two decades of building the Southwest, one project at a time.</p>
                    </div>
                    <Timeline events={timelineEvents} />
                </div>
            </section>

            {/* Leadership Section */}
            <LeadershipSection />

            {/* Team Section */}
            <TeamSection />

            {/* CTA Section */}
            <section className={styles.ctaSection}>
                <div className="container">
                    <div className={styles.ctaContent}>
                        <h2>Sick of subcontractor headaches?</h2>
                        <p>Let us fix that</p>
                        <a href="/contact" className={styles.ctaButton}>Get in Touch</a>
                    </div>
                </div>
            </section>

            {/* Drone Team Photo */}
            <section className={styles.droneSection}>
                <div className={styles.droneHeader}>
                    <span className={styles.droneEyebrow}>One Team</span>
                    <h2>The Canyon State Team</h2>
                    <div className={styles.droneDivider} aria-hidden="true" />
                </div>
                <img
                    src={droneTeamImg}
                    alt="The Canyon State Enterprises team"
                    className={styles.droneImg}
                    loading="lazy"
                />
            </section>
        </div>
    );
};

export default About;
