/**
 * Generate public/sitemap.xml from the React app's route + data sources.
 *
 * Run with: `node scripts/generate-sitemap.mjs`
 * Also wired into `npm run build` via the `prebuild` script in package.json,
 * so Netlify always deploys a fresh sitemap.
 *
 * Why regex parsing instead of importing the data modules?
 * src/data/projects.js imports binary .webp assets — those resolve under
 * Vite but blow up in plain Node. Regex over the source text is robust
 * enough for our flat data shape and avoids hauling in a bundler just to
 * read a list of IDs.
 */

import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __dirname    = path.dirname(fileURLToPath(import.meta.url));
const projectRoot  = path.resolve(__dirname, '..');
const SITE         = 'https://canyonstateaz.com';
const TODAY        = new Date().toISOString().slice(0, 10);

// ── Static routes (mirror App.jsx <Route> entries) ────────────────────────
const STATIC = [
    { p: '/',                     pri: 1.0,  cf: 'monthly' },
    { p: '/about',                pri: 0.9,  cf: 'monthly' },
    { p: '/services',             pri: 0.9,  cf: 'monthly' },
    { p: '/partnerships',         pri: 0.8,  cf: 'monthly' },
    { p: '/where',                pri: 0.8,  cf: 'yearly'  },
    { p: '/contact',              pri: 0.9,  cf: 'yearly'  },
    { p: '/careers',              pri: 0.9,  cf: 'weekly'  },
    { p: '/faq',                  pri: 0.7,  cf: 'monthly' },
    { p: '/privacy',              pri: 0.3,  cf: 'yearly'  },
    { p: '/terms',                pri: 0.3,  cf: 'yearly'  },
    { p: '/portfolio',            pri: 0.8,  cf: 'monthly' },
    { p: '/portfolio/commercial', pri: 0.8,  cf: 'monthly' },
    { p: '/portfolio/residential',pri: 0.8,  cf: 'monthly' },
    { p: '/blog',                 pri: 0.85, cf: 'weekly'  },
];

// ── Trade pages (must match Navbar.jsx TRADES) ────────────────────────────
const TRADES = [
    { id: 'roofing',             pri: 0.85 },
    { id: 'stucco',              pri: 0.85 },
    { id: 'general-contracting', pri: 0.80 },
    { id: 'hvac',                pri: 0.80 },
    { id: 'plumbing',            pri: 0.80 },
    { id: 'res-const',           pri: 0.80 },
    { id: 'com-const',           pri: 0.80 },
    { id: 'metals',              pri: 0.75 },
    { id: 'masonry',             pri: 0.75 },
    { id: 'fencing',             pri: 0.75 },
    { id: 'gutters',             pri: 0.75 },
    { id: 'land-dev',            pri: 0.75 },
];

// ── Location IDs (scrape from src/data/locations.js) ──────────────────────
const locationsSrc = fs.readFileSync(path.join(projectRoot, 'src/data/locations.js'), 'utf8');
const locationIds = [
    ...locationsSrc.matchAll(/\bid:\s*['"]([a-z0-9-]+)['"]/g),
].map(m => m[1]);

// ── Project IDs (scrape from src/data/projects.js) ─────────────────────────
// Match only entries whose id is followed by a `name:` field — that filters
// out the COMMERCIAL_CATEGORIES / RESIDENTIAL_CATEGORIES entries which have
// `id` + `label` but never `name`.
const projectsSrc = fs.readFileSync(path.join(projectRoot, 'src/data/projects.js'), 'utf8');
const projectIds = [
    ...projectsSrc.matchAll(/\bid:\s*['"]([a-z0-9-]+)['"]\s*,\s*name:/g),
].map(m => m[1]);

// ── Blog post slugs (scrape from src/data/blog.js) ────────────────────────
const blogSrc = fs.readFileSync(path.join(projectRoot, 'src/data/blog.js'), 'utf8');
const blogSlugs = [
    ...blogSrc.matchAll(/\bslug:\s*['"]([a-z0-9-]+)['"]/g),
].map(m => m[1]);

// ── Build URL list ────────────────────────────────────────────────────────
const urls = [];
for (const r of STATIC)         urls.push({ loc: SITE + r.p,                lastmod: TODAY, cf: r.cf,        pri: r.pri  });
for (const t of TRADES)         urls.push({ loc: SITE + '/services/' + t.id, lastmod: TODAY, cf: 'monthly',   pri: t.pri  });
for (const id of locationIds)   urls.push({ loc: SITE + '/locations/' + id,  lastmod: TODAY, cf: 'monthly',   pri: 0.70  });
for (const id of projectIds)    urls.push({ loc: SITE + '/portfolio/' + id,  lastmod: TODAY, cf: 'yearly',    pri: 0.50  });
for (const s  of blogSlugs)     urls.push({ loc: SITE + '/blog/' + s,        lastmod: TODAY, cf: 'monthly',   pri: 0.75  });

// ── Serialize ──────────────────────────────────────────────────────────────
const xml =
`<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by scripts/generate-sitemap.mjs — do not edit by hand. -->
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${urls.map(u =>
`    <url>
        <loc>${u.loc}</loc>
        <lastmod>${u.lastmod}</lastmod>
        <changefreq>${u.cf}</changefreq>
        <priority>${u.pri.toFixed(2)}</priority>
    </url>`).join('\n')}
</urlset>
`;

const outPath = path.join(projectRoot, 'public/sitemap.xml');
fs.writeFileSync(outPath, xml, 'utf8');

console.log(`✓ wrote public/sitemap.xml`);
console.log(`  ${STATIC.length} static + ${TRADES.length} trade + ${locationIds.length} location + ${projectIds.length} project + ${blogSlugs.length} blog = ${urls.length} URLs`);
